- name: Update APT package cache
  apt:
    update_cache: yes
    upgrade: yes

- name: Upgrade APT to the lastest packages
  apt:
    name: "*"
    state: latest

- name: Install role-independent useful system packages
  apt: >
    pkg={{','.join(common_debian_pkgs)}} install_recommends=yes
    state=present update_cache=yes
